FROM node:26.4.0-alpine3.24

WORKDIR /app

RUN apk add --no-cache libc6-compat chromium nss freetype harfbuzz ca-certificates ttf-freefont

ENV CHROMIUM_PATH=/usr/bin/chromium
ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
ENV NEXT_TELEMETRY_DISABLED=1

COPY package.json ./
RUN npm install --legacy-peer-deps

EXPOSE 3000

CMD ["npm", "run", "dev"]
