import type { ResumeData } from "@/types";
import { createZip } from "./zip";

export async function exportEvidencePack(data: ResumeData, score?: number): Promise<void> {
  const timestamp = new Date().toISOString();
  const name = data.personal.name || "candidate";

  const metadata = {
    candidateName: data.personal.name || "",
    exportedAt: timestamp,
    atsScore: score ?? 0,
    totalSections: countSections(data),
    version: "1.0.0",
  };

  const readme = [
    "CareerForge AI — Evidence Pack",
    "==============================",
    "",
    `Candidate: ${data.personal.name || "N/A"}`,
    `Exported: ${timestamp}`,
    `ATS Score: ${score ?? "N/A"}`,
    "",
    "Contents:",
    "  resume-original.json   — Your original resume data as structured JSON",
    "  resume-optimized.json  — The optimized/current resume data",
    "  cover-letter.md        — A generated cover letter based on your profile",
    "  metadata.json          — Export timestamp, score, and version info",
    "",
    "This pack is intended for job applications, portfolio archives,",
    "or sharing with career coaches.",
  ].join("\n");

  const coverLetter = generateCoverLetter(data);

  const zip = createZip([
    { name: "resume-original.json", content: JSON.stringify(data, null, 2) },
    { name: "resume-optimized.json", content: JSON.stringify(data, null, 2) },
    { name: "cover-letter.md", content: coverLetter },
    { name: "metadata.json", content: JSON.stringify(metadata, null, 2) },
    { name: "README.txt", content: readme },
  ]);

  const url = URL.createObjectURL(zip);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${name.replace(/\s+/g, "-")}-evidence-pack.zip`;
  a.click();
  URL.revokeObjectURL(url);
}

function countSections(data: ResumeData): number {
  let count = 0;
  if (data.personal.name) count++;
  if (data.experience.length > 0) count++;
  if (data.education.length > 0) count++;
  if (data.skills.length > 0) count++;
  if (data.certifications.length > 0) count++;
  if (data.projects.length > 0) count++;
  if (data.languages.length > 0) count++;
  return count;
}

function generateCoverLetter(data: ResumeData): string {
  const name = data.personal.name || "Applicant";
  const role = data.experience[0]?.position || "the position";
  const company = data.experience[0]?.company || "your company";
  const skills = data.skills.flatMap((c) => c.skills).slice(0, 5);

  return [
    `# Cover Letter — ${name}`,
    "",
    `Dear Hiring Manager,`,
    "",
    `I am writing to express my strong interest in the ${role} role at ${company}.`,
    `With a proven track record in software engineering and a passion for building`,
    `impactful products, I am confident that my experience aligns perfectly with`,
    `your team's needs.`,
    "",
    skills.length > 0
      ? `My core competencies include ${skills.join(", ")}, which I have applied`
      : "I have applied my technical expertise",
    `across multiple projects to deliver measurable results.`,
    "",
    `I would welcome the opportunity to discuss how my background and skills`,
    `can contribute to the success of ${company}.`,
    "",
    "Best regards,",
    name,
    "",
    `---`,
    `Generated by CareerForge AI on ${new Date().toISOString().split("T")[0]}`,
  ].join("\n");
}
